from app.services.inventory_service import check_stock, reserve_stock, release_stock
from app.services.location_service import calculate_distance, get_nearby_branches
from app.services.diagnostic_service import search_diseases, diagnostic_search, suggest_correction
from app.services.nutrition_service import calculate_feed_and_water, get_feed_phase