"""creacion_limpia_total

Revision ID: 4189208a6c92
Revises: 
Create Date: 2026-06-28 20:09:03.227126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4189208a6c92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_aveologia',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('orden', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    with op.batch_alter_table('categorias_aveologia', schema=None) as batch_op:
        batch_op.create_index('idx_orden', ['orden'], unique=False)

    op.create_table('categorias_producto',
    sa.Column('id_categoria_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='Para subcategorías'),
    sa.Column('orden', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categorias_producto.id_categoria_producto'], name='categorias_producto_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_categoria_producto')
    )
    with op.batch_alter_table('categorias_producto', schema=None) as batch_op:
        batch_op.create_index('idx_parent', ['parent_id'], unique=False)
        batch_op.create_index('idx_slug', ['slug'], unique=False)
        batch_op.create_index('nombre_categoria', ['nombre_categoria'], unique=True)
        batch_op.create_index('slug', ['slug'], unique=True)

    op.create_table('configuracion_sistema',
    sa.Column('id_config', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('tipo_dato', sa.Enum('string', 'Integer', 'boolean', 'json', name='configuracionsistematipodato'), server_default=sa.text("'string'"), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_config')
    )
    with op.batch_alter_table('configuracion_sistema', schema=None) as batch_op:
        batch_op.create_index('clave', ['clave'], unique=True)
        batch_op.create_index('idx_clave', ['clave'], unique=False)
        batch_op.create_index('idx_grupo', ['grupo'], unique=False)

    op.create_table('diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('prevention', sa.Text(), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enfermedades',
    sa.Column('id_enfermedad', sa.Integer(), nullable=False),
    sa.Column('nombre_enfermedad', sa.String(length=200), nullable=False),
    sa.Column('tipo_enfermedad', sa.Enum('viral', 'bacteriana', 'parasitaria', 'fungica', 'nutricional', 'ambiental', name='enfermedadestipoenfermedad'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('nombre_cientifico', sa.String(length=200), nullable=True),
    sa.Column('causas', sa.Text(), nullable=True),
    sa.Column('prevencion', sa.Text(), nullable=True),
    sa.Column('contagiosidad', sa.Enum('no_contagioso', 'baja', 'media', 'alta', name='enfermedadescontagiosidad'), server_default=sa.text("'media'"), nullable=True),
    sa.Column('mortalidad_estimada', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Porcentaje de mortalidad'),
    sa.Column('edad_susceptible', sa.String(length=100), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id_enfermedad')
    )
    with op.batch_alter_table('enfermedades', schema=None) as batch_op:
        batch_op.create_index('ft_enfermedades', ['nombre_enfermedad', 'nombre_cientifico', 'descripcion'], unique=False)
        batch_op.create_index('idx_tipo', ['tipo_enfermedad'], unique=False)

    op.create_table('estados_pedido',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=7), server_default=sa.text("'#6c757d'"), nullable=True),
    sa.Column('orden', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('es_final', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='Estado terminal (entregado, cancelado)'),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id_estado')
    )
    with op.batch_alter_table('estados_pedido', schema=None) as batch_op:
        batch_op.create_index('idx_orden', ['orden'], unique=False)
        batch_op.create_index('nombre_estado', ['nombre_estado'], unique=True)

    op.create_table('etapas_vida',
    sa.Column('id_etapa', sa.Integer(), nullable=False),
    sa.Column('nombre_etapa', sa.String(length=100), nullable=False),
    sa.Column('edad_inicio_dias', sa.Integer(), nullable=False),
    sa.Column('edad_fin_dias', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.CheckConstraint('edad_fin_dias > edad_inicio_dias', name='CONSTRAINT_1'),
    sa.PrimaryKeyConstraint('id_etapa')
    )
    with op.batch_alter_table('etapas_vida', schema=None) as batch_op:
        batch_op.create_index('idx_orden', ['orden'], unique=False)

    op.create_table('feed_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_week', sa.Integer(), nullable=False),
    sa.Column('max_week', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genetic_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodos_entrega',
    sa.Column('id_metodo_entrega', sa.Integer(), nullable=False),
    sa.Column('nombre_metodo', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('costo_base', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('(0.00)'), nullable=True),
    sa.Column('costo_por_km', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('(0.00)'), nullable=True),
    sa.Column('tiempo_estimado_horas', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id_metodo_entrega')
    )
    with op.batch_alter_table('metodos_entrega', schema=None) as batch_op:
        batch_op.create_index('nombre_metodo', ['nombre_metodo'], unique=True)

    op.create_table('permisos',
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('nombre_permiso', sa.String(length=100), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_permiso')
    )
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.create_index('idx_modulo', ['modulo'], unique=False)
        batch_op.create_index('nombre_permiso', ['nombre_permiso'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.Column('nivel_acceso', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('nombre_rol', ['nombre_rol'], unique=True)
        batch_op.create_index('uk_nombre_rol', ['nombre_rol'], unique=True)

    op.create_table('sintomas',
    sa.Column('id_sintoma', sa.Integer(), nullable=False),
    sa.Column('nombre_sintoma', sa.String(length=150), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('gravedad', sa.Enum('leve', 'moderado', 'grave', 'critico', name='sintomasgravedad'), server_default=sa.text("'moderado'"), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True, comment='Palabras clave para búsqueda semántica'),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id_sintoma')
    )
    with op.batch_alter_table('sintomas', schema=None) as batch_op:
        batch_op.create_index('ft_sintomas', ['nombre_sintoma', 'descripcion', 'keywords'], unique=False)
        batch_op.create_index('idx_gravedad', ['gravedad'], unique=False)

    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_ave',
    sa.Column('id_tipo_ave', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo', sa.String(length=100), nullable=False),
    sa.Column('proposito', sa.Enum('carne', 'huevos', 'dual', 'ornamental', name='tiposaveproposito'), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_ave')
    )
    with op.batch_alter_table('tipos_ave', schema=None) as batch_op:
        batch_op.create_index('nombre_tipo', ['nombre_tipo'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('diagnostic_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_id', 'symptom_id', name='uq_disease_symptom')
    )
    with op.batch_alter_table('diagnostic_matrix', schema=None) as batch_op:
        batch_op.create_index('idx_matrix_disease_symptom', ['disease_id', 'symptom_id'], unique=False)

    op.create_table('growth_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genetic_line_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('daily_feed_grams', sa.Float(), nullable=False),
    sa.Column('daily_water_ml', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['genetic_line_id'], ['genetic_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genetic_line_id', 'week', name='uq_genetic_line_week')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('delivery_type', sa.String(length=20), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('verification_code', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_code')
    )
    op.create_table('parametros_nutricionales',
    sa.Column('id_parametro', sa.Integer(), nullable=False),
    sa.Column('id_tipo_ave', sa.Integer(), nullable=False),
    sa.Column('id_etapa', sa.Integer(), nullable=False),
    sa.Column('consumo_alimento_gr_dia', sa.DECIMAL(precision=8, scale=2), nullable=False, comment='Gramos por ave por día'),
    sa.Column('consumo_agua_ml_dia', sa.DECIMAL(precision=8, scale=2), nullable=False, comment='Mililitros por ave por día'),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('proteina_porcentaje', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('energia_kcal', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_etapa'], ['etapas_vida.id_etapa'], name='parametros_nutricionales_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tipo_ave'], ['tipos_ave.id_tipo_ave'], name='parametros_nutricionales_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_parametro')
    )
    with op.batch_alter_table('parametros_nutricionales', schema=None) as batch_op:
        batch_op.create_index('id_etapa', ['id_etapa'], unique=False)
        batch_op.create_index('uk_tipo_etapa', ['id_tipo_ave', 'id_etapa'], unique=True)

    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_categoria_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('codigo_producto', sa.String(length=50), nullable=True),
    sa.Column('descripcion_corta', sa.Text(), nullable=True),
    sa.Column('descripcion_larga', sa.Text(), nullable=True),
    sa.Column('precio_oferta', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unidad_medida', sa.Enum('unidad', 'kg', 'lb', 'docena', 'caja', 'saco', name='productosunidadmedida'), server_default=sa.text("'unidad'"), nullable=True),
    sa.Column('peso_gramos', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('stock_total', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='Stock total en granja central'),
    sa.Column('stock_minimo', sa.Integer(), server_default=sa.text('5'), nullable=True),
    sa.Column('requiere_refrigeracion', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('dias_frescura', sa.Integer(), nullable=True, comment='Días de vida útil del producto'),
    sa.Column('destacado', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_producto'], ['categorias_producto.id_categoria_producto'], name='productos_ibfk_1'),
    sa.PrimaryKeyConstraint('id_producto')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index('codigo_producto', ['codigo_producto'], unique=True)
        batch_op.create_index('ft_productos', ['nombre_producto', 'descripcion_corta'], unique=False)
        batch_op.create_index('idx_activo', ['activo'], unique=False)
        batch_op.create_index('idx_categoria', ['id_categoria_producto'], unique=False)
        batch_op.create_index('idx_destacado', ['destacado'], unique=False)
        batch_op.create_index('idx_slug', ['slug'], unique=False)
        batch_op.create_index('slug', ['slug'], unique=True)

    op.create_table('remedios',
    sa.Column('id_remedio', sa.Integer(), nullable=False),
    sa.Column('nombre_remedio', sa.String(length=200), nullable=False),
    sa.Column('tipo_remedio', sa.Enum('casero', 'herbal', 'preventivo', 'paliativo', name='remediostiporemedio'), nullable=False),
    sa.Column('ingredientes', sa.Text(), nullable=False),
    sa.Column('preparacion', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_enfermedad', sa.Integer(), nullable=True),
    sa.Column('modo_uso', sa.Text(), nullable=True),
    sa.Column('efectividad_estimada', sa.Enum('baja', 'media', 'alta', name='remediosefectividadestimada'), server_default=sa.text("'media'"), nullable=True),
    sa.Column('contraindicaciones', sa.Text(), nullable=True),
    sa.Column('nota_importante', sa.Text(), nullable=True, comment='Advertencias de seguridad'),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['id_enfermedad'], ['enfermedades.id_enfermedad'], name='remedios_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_remedio')
    )
    with op.batch_alter_table('remedios', schema=None) as batch_op:
        batch_op.create_index('idx_enfermedad', ['id_enfermedad'], unique=False)
        batch_op.create_index('idx_tipo', ['tipo_remedio'], unique=False)

    op.create_table('roles_permisos',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['permisos.id_permiso'], name='roles_permisos_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], name='roles_permisos_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso')
    )
    with op.batch_alter_table('roles_permisos', schema=None) as batch_op:
        batch_op.create_index('id_permiso', ['id_permiso'], unique=False)

    op.create_table('sintomas_enfermedades',
    sa.Column('id_enfermedad', sa.Integer(), nullable=False),
    sa.Column('id_sintoma', sa.Integer(), nullable=False),
    sa.Column('frecuencia', sa.Enum('raro', 'ocasional', 'frecuente', 'muy_frecuente', name='sintomasenfermedadesfrecuencia'), server_default=sa.text("'frecuente'"), nullable=True),
    sa.Column('intensidad', sa.Enum('leve', 'moderado', 'severo', name='sintomasenfermedadesintensidad'), server_default=sa.text("'moderado'"), nullable=True),
    sa.ForeignKeyConstraint(['id_enfermedad'], ['enfermedades.id_enfermedad'], name='sintomas_enfermedades_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_sintoma'], ['sintomas.id_sintoma'], name='sintomas_enfermedades_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_enfermedad', 'id_sintoma')
    )
    with op.batch_alter_table('sintomas_enfermedades', schema=None) as batch_op:
        batch_op.create_index('id_sintoma', ['id_sintoma'], unique=False)

    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'branch_id', name='uq_product_branch')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index('idx_stock_product_branch', ['product_id', 'branch_id'], unique=False)

    op.create_table('tratamientos',
    sa.Column('id_tratamiento', sa.Integer(), nullable=False),
    sa.Column('id_enfermedad', sa.Integer(), nullable=False),
    sa.Column('nombre_tratamiento', sa.String(length=200), nullable=False),
    sa.Column('tipo_tratamiento', sa.Enum('medicamento', 'vacuna', 'manejo', 'nutricional', 'quirurgico', name='tratamientostipotratamiento'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dosificacion', sa.Text(), nullable=True),
    sa.Column('duracion', sa.String(length=100), nullable=True),
    sa.Column('efectividad', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Porcentaje de efectividad'),
    sa.Column('costo_aproximado', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('advertencias', sa.Text(), nullable=True),
    sa.Column('requiere_veterinario', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('orden_recomendacion', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['id_enfermedad'], ['enfermedades.id_enfermedad'], name='tratamientos_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_tratamiento')
    )
    with op.batch_alter_table('tratamientos', schema=None) as batch_op:
        batch_op.create_index('idx_enfermedad', ['id_enfermedad'], unique=False)
        batch_op.create_index('idx_tipo', ['tipo_tratamiento'], unique=False)

    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=255), server_default=sa.text("'default-avatar.png'"), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('verificado', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('token_verificacion', sa.String(length=100), nullable=True),
    sa.Column('token_recuperacion', sa.String(length=100), nullable=True),
    sa.Column('fecha_token_expira', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], name='usuarios_ibfk_1'),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.create_index('idx_activo', ['activo'], unique=False)
        batch_op.create_index('idx_email', ['email'], unique=False)
        batch_op.create_index('idx_rol', ['id_rol'], unique=False)

    op.create_table('articulos_aveologia',
    sa.Column('id_articulo', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('imagen_principal', sa.String(length=255), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('visitas', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('destacado', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id_usuario'], name='articulos_aveologia_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias_aveologia.id_categoria'], name='articulos_aveologia_ibfk_1'),
    sa.PrimaryKeyConstraint('id_articulo')
    )
    with op.batch_alter_table('articulos_aveologia', schema=None) as batch_op:
        batch_op.create_index('autor_id', ['autor_id'], unique=False)
        batch_op.create_index('ft_busqueda', ['titulo', 'contenido', 'tags'], unique=False)
        batch_op.create_index('idx_categoria', ['id_categoria'], unique=False)
        batch_op.create_index('idx_destacado', ['destacado'], unique=False)
        batch_op.create_index('idx_slug', ['slug'], unique=False)
        batch_op.create_index('slug', ['slug'], unique=True)

    op.create_table('atributos_producto',
    sa.Column('id_atributo', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_atributo', sa.String(length=100), nullable=False, comment='Ej: raza, calibre, edad'),
    sa.Column('valor_atributo', sa.String(length=255), nullable=False, comment='Ej: Rhode Island, Jumbo, 1 día'),
    sa.Column('grupo_atributo', sa.String(length=50), nullable=True, comment='Para agrupar atributos similares'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='atributos_producto_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_atributo')
    )
    with op.batch_alter_table('atributos_producto', schema=None) as batch_op:
        batch_op.create_index('idx_nombre', ['nombre_atributo'], unique=False)
        batch_op.create_index('idx_producto', ['id_producto'], unique=False)

    op.create_table('carrito',
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('fecha_agregado', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='Para usuarios no logueados'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='carrito_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='carrito_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_carrito')
    )
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.create_index('id_producto', ['id_producto'], unique=False)
        batch_op.create_index('idx_session', ['session_id'], unique=False)
        batch_op.create_index('idx_usuario', ['id_usuario'], unique=False)

    op.create_table('historial_calculos',
    sa.Column('id_calculo', sa.Integer(), nullable=False),
    sa.Column('id_tipo_ave', sa.Integer(), nullable=False),
    sa.Column('id_etapa', sa.Integer(), nullable=False),
    sa.Column('cantidad_aves', sa.Integer(), nullable=False),
    sa.Column('edad_dias', sa.Integer(), nullable=False),
    sa.Column('fecha_calculo', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('resultado_alimento_kg', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('resultado_agua_litros', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_etapa'], ['etapas_vida.id_etapa'], name='historial_calculos_ibfk_3'),
    sa.ForeignKeyConstraint(['id_tipo_ave'], ['tipos_ave.id_tipo_ave'], name='historial_calculos_ibfk_2'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='historial_calculos_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_calculo')
    )
    with op.batch_alter_table('historial_calculos', schema=None) as batch_op:
        batch_op.create_index('id_etapa', ['id_etapa'], unique=False)
        batch_op.create_index('id_tipo_ave', ['id_tipo_ave'], unique=False)
        batch_op.create_index('idx_fecha', ['fecha_calculo'], unique=False)
        batch_op.create_index('idx_usuario', ['id_usuario'], unique=False)

    op.create_table('imagenes_producto',
    sa.Column('id_imagen', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('es_principal', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('orden', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='imagenes_producto_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    with op.batch_alter_table('imagenes_producto', schema=None) as batch_op:
        batch_op.create_index('idx_principal', ['es_principal'], unique=False)
        batch_op.create_index('idx_producto', ['id_producto'], unique=False)

    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tipo_notificacion', sa.Enum('pedido', 'sistema', 'promocion', 'alerta', name='notificacionestiponotificacion'), server_default=sa.text("'sistema'"), nullable=True),
    sa.Column('enlace', sa.String(length=255), nullable=True),
    sa.Column('leida', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='notificaciones_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index('idx_fecha', ['fecha_creacion'], unique=False)
        batch_op.create_index('idx_leida', ['leida'], unique=False)
        batch_op.create_index('idx_usuario', ['id_usuario'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesiones_usuario',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('token_sesion', sa.String(length=255), nullable=False),
    sa.Column('fecha_inicio', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('activa', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='sesiones_usuario_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    with op.batch_alter_table('sesiones_usuario', schema=None) as batch_op:
        batch_op.create_index('idx_token', ['token_sesion'], unique=False)
        batch_op.create_index('idx_usuario', ['id_usuario'], unique=False)
        batch_op.create_index('token_sesion', ['token_sesion'], unique=True)

    op.create_table('sucursales',
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.Column('codigo_sucursal', sa.String(length=20), nullable=False),
    sa.Column('nombre_sucursal', sa.String(length=200), nullable=False),
    sa.Column('direccion_completa', sa.Text(), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('latitud', sa.DECIMAL(precision=10, scale=8), nullable=False, comment='Para geolocalización'),
    sa.Column('longitud', sa.DECIMAL(precision=11, scale=8), nullable=False, comment='Para geolocalización'),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_encargado', sa.Integer(), nullable=True, comment='Usuario responsable de la sucursal'),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('capacidad_almacenamiento', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='En metros cúbicos o kg'),
    sa.Column('horario_apertura', sa.Time(), nullable=True),
    sa.Column('horario_cierre', sa.Time(), nullable=True),
    sa.Column('dias_atencion', sa.String(length=100), server_default=sa.text("'Lunes a Sábado'"), nullable=True),
    sa.Column('permite_delivery', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('permite_pickup', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('radio_cobertura_km', sa.DECIMAL(precision=5, scale=2), server_default=sa.text('(10.00)'), nullable=True, comment='Radio de delivery'),
    sa.Column('imagen_fachada', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('fecha_apertura', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_encargado'], ['usuarios.id_usuario'], name='sucursales_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_sucursal')
    )
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.create_index('codigo_sucursal', ['codigo_sucursal'], unique=True)
        batch_op.create_index('id_encargado', ['id_encargado'], unique=False)
        batch_op.create_index('idx_activo', ['activo'], unique=False)
        batch_op.create_index('idx_ciudad', ['ciudad'], unique=False)
        batch_op.create_index('idx_coords', ['latitud', 'longitud'], unique=False)

    op.create_table('horarios_sucursal',
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo', name='horariossucursaldiasemana'), nullable=False),
    sa.Column('hora_apertura', sa.Time(), nullable=False),
    sa.Column('hora_cierre', sa.Time(), nullable=False),
    sa.Column('cerrado', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursales.id_sucursal'], name='horarios_sucursal_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_horario')
    )
    with op.batch_alter_table('horarios_sucursal', schema=None) as batch_op:
        batch_op.create_index('uk_sucursal_dia', ['id_sucursal', 'dia_semana'], unique=True)

    op.create_table('inventario_sucursal',
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cantidad_reservada', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='Productos en pedidos pendientes'),
    sa.Column('stock_minimo', sa.Integer(), server_default=sa.text('5'), nullable=True),
    sa.Column('stock_maximo', sa.Integer(), nullable=True),
    sa.Column('ultima_reposicion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='inventario_sucursal_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursales.id_sucursal'], name='inventario_sucursal_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_inventario')
    )
    with op.batch_alter_table('inventario_sucursal', schema=None) as batch_op:
        batch_op.create_index('idx_producto', ['id_producto'], unique=False)
        batch_op.create_index('idx_sucursal', ['id_sucursal'], unique=False)
        batch_op.create_index('uk_sucursal_producto', ['id_sucursal', 'id_producto'], unique=True)

    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=20), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_sucursal', sa.Integer(), nullable=False, comment='Sucursal asignada para el pedido'),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('id_metodo_entrega', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pedido', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('direccion_entrega', sa.Text(), nullable=True),
    sa.Column('ciudad_entrega', sa.String(length=100), nullable=True),
    sa.Column('departamento_entrega', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal_entrega', sa.String(length=10), nullable=True),
    sa.Column('latitud_entrega', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitud_entrega', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('distancia_km', sa.DECIMAL(precision=6, scale=2), nullable=True, comment='Distancia desde sucursal a cliente'),
    sa.Column('nombre_receptor', sa.String(length=150), nullable=True),
    sa.Column('telefono_receptor', sa.String(length=20), nullable=True),
    sa.Column('email_receptor', sa.String(length=150), nullable=True),
    sa.Column('notas_cliente', sa.Text(), nullable=True),
    sa.Column('costo_envio', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('(0.00)'), nullable=True),
    sa.Column('descuento', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('(0.00)'), nullable=True),
    sa.Column('fecha_estimada_entrega', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_real', sa.DateTime(), nullable=True),
    sa.Column('comprobante_pago', sa.String(length=255), nullable=True),
    sa.Column('metodo_pago', sa.Enum('efectivo', 'tarjeta', 'transferencia', 'yape', 'plin', name='pedidosmetodopago'), server_default=sa.text("'efectivo'"), nullable=True),
    sa.Column('pagado', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.id_usuario'], name='pedidos_ibfk_1'),
    sa.ForeignKeyConstraint(['id_estado'], ['estados_pedido.id_estado'], name='pedidos_ibfk_3'),
    sa.ForeignKeyConstraint(['id_metodo_entrega'], ['metodos_entrega.id_metodo_entrega'], name='pedidos_ibfk_4'),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursales.id_sucursal'], name='pedidos_ibfk_2'),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index('id_metodo_entrega', ['id_metodo_entrega'], unique=False)
        batch_op.create_index('idx_cliente', ['id_cliente'], unique=False)
        batch_op.create_index('idx_estado', ['id_estado'], unique=False)
        batch_op.create_index('idx_fecha', ['fecha_pedido'], unique=False)
        batch_op.create_index('idx_numero', ['numero_pedido'], unique=False)
        batch_op.create_index('idx_sucursal', ['id_sucursal'], unique=False)
        batch_op.create_index('numero_pedido', ['numero_pedido'], unique=True)

    op.create_table('calificaciones',
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha_calificacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('calificacion_producto', sa.Integer(), nullable=True),
    sa.Column('calificacion_servicio', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('respuesta_vendedor', sa.Text(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('aprobado', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.id_usuario'], name='calificaciones_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], name='calificaciones_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='calificaciones_ibfk_3', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    with op.batch_alter_table('calificaciones', schema=None) as batch_op:
        batch_op.create_index('id_cliente', ['id_cliente'], unique=False)
        batch_op.create_index('idx_aprobado', ['aprobado'], unique=False)
        batch_op.create_index('idx_pedido', ['id_pedido'], unique=False)
        batch_op.create_index('idx_producto', ['id_producto'], unique=False)

    op.create_table('detalle_pedido',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], name='detalle_pedido_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='detalle_pedido_ibfk_2'),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.create_index('idx_pedido', ['id_pedido'], unique=False)
        batch_op.create_index('idx_producto', ['id_producto'], unique=False)

    op.create_table('historial_pedido',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True, comment='Usuario que realizó el cambio'),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_estado'], ['estados_pedido.id_estado'], name='historial_pedido_ibfk_2'),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], name='historial_pedido_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='historial_pedido_ibfk_3', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_historial')
    )
    with op.batch_alter_table('historial_pedido', schema=None) as batch_op:
        batch_op.create_index('id_estado', ['id_estado'], unique=False)
        batch_op.create_index('id_usuario', ['id_usuario'], unique=False)
        batch_op.create_index('idx_fecha', ['fecha_cambio'], unique=False)
        batch_op.create_index('idx_pedido', ['id_pedido'], unique=False)

    op.create_table('movimientos_inventario',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('entrada', 'salida', 'ajuste', 'transferencia', 'devolucion', name='movimientosinventariotipomovimiento'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_movimiento', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True, comment='Usuario que realizó el movimiento'),
    sa.Column('id_pedido', sa.Integer(), nullable=True, comment='Si es por una venta'),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_inventario'], ['inventario_sucursal.id_inventario'], name='movimientos_inventario_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='movimientos_inventario_ibfk_2', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.create_index('id_usuario', ['id_usuario'], unique=False)
        batch_op.create_index('idx_fecha', ['fecha_movimiento'], unique=False)
        batch_op.create_index('idx_inventario', ['id_inventario'], unique=False)
        batch_op.create_index('idx_tipo', ['tipo_movimiento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_index('idx_tipo')
        batch_op.drop_index('idx_inventario')
        batch_op.drop_index('idx_fecha')
        batch_op.drop_index('id_usuario')

    op.drop_table('movimientos_inventario')
    with op.batch_alter_table('historial_pedido', schema=None) as batch_op:
        batch_op.drop_index('idx_pedido')
        batch_op.drop_index('idx_fecha')
        batch_op.drop_index('id_usuario')
        batch_op.drop_index('id_estado')

    op.drop_table('historial_pedido')
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.drop_index('idx_producto')
        batch_op.drop_index('idx_pedido')

    op.drop_table('detalle_pedido')
    with op.batch_alter_table('calificaciones', schema=None) as batch_op:
        batch_op.drop_index('idx_producto')
        batch_op.drop_index('idx_pedido')
        batch_op.drop_index('idx_aprobado')
        batch_op.drop_index('id_cliente')

    op.drop_table('calificaciones')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index('numero_pedido')
        batch_op.drop_index('idx_sucursal')
        batch_op.drop_index('idx_numero')
        batch_op.drop_index('idx_fecha')
        batch_op.drop_index('idx_estado')
        batch_op.drop_index('idx_cliente')
        batch_op.drop_index('id_metodo_entrega')

    op.drop_table('pedidos')
    with op.batch_alter_table('inventario_sucursal', schema=None) as batch_op:
        batch_op.drop_index('uk_sucursal_producto')
        batch_op.drop_index('idx_sucursal')
        batch_op.drop_index('idx_producto')

    op.drop_table('inventario_sucursal')
    with op.batch_alter_table('horarios_sucursal', schema=None) as batch_op:
        batch_op.drop_index('uk_sucursal_dia')

    op.drop_table('horarios_sucursal')
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.drop_index('idx_coords')
        batch_op.drop_index('idx_ciudad')
        batch_op.drop_index('idx_activo')
        batch_op.drop_index('id_encargado')
        batch_op.drop_index('codigo_sucursal')

    op.drop_table('sucursales')
    with op.batch_alter_table('sesiones_usuario', schema=None) as batch_op:
        batch_op.drop_index('token_sesion')
        batch_op.drop_index('idx_usuario')
        batch_op.drop_index('idx_token')

    op.drop_table('sesiones_usuario')
    op.drop_table('order_items')
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index('idx_usuario')
        batch_op.drop_index('idx_leida')
        batch_op.drop_index('idx_fecha')

    op.drop_table('notificaciones')
    with op.batch_alter_table('imagenes_producto', schema=None) as batch_op:
        batch_op.drop_index('idx_producto')
        batch_op.drop_index('idx_principal')

    op.drop_table('imagenes_producto')
    with op.batch_alter_table('historial_calculos', schema=None) as batch_op:
        batch_op.drop_index('idx_usuario')
        batch_op.drop_index('idx_fecha')
        batch_op.drop_index('id_tipo_ave')
        batch_op.drop_index('id_etapa')

    op.drop_table('historial_calculos')
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.drop_index('idx_usuario')
        batch_op.drop_index('idx_session')
        batch_op.drop_index('id_producto')

    op.drop_table('carrito')
    with op.batch_alter_table('atributos_producto', schema=None) as batch_op:
        batch_op.drop_index('idx_producto')
        batch_op.drop_index('idx_nombre')

    op.drop_table('atributos_producto')
    with op.batch_alter_table('articulos_aveologia', schema=None) as batch_op:
        batch_op.drop_index('slug')
        batch_op.drop_index('idx_slug')
        batch_op.drop_index('idx_destacado')
        batch_op.drop_index('idx_categoria')
        batch_op.drop_index('ft_busqueda')
        batch_op.drop_index('autor_id')

    op.drop_table('articulos_aveologia')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('idx_rol')
        batch_op.drop_index('idx_email')
        batch_op.drop_index('idx_activo')
        batch_op.drop_index('email')

    op.drop_table('usuarios')
    with op.batch_alter_table('tratamientos', schema=None) as batch_op:
        batch_op.drop_index('idx_tipo')
        batch_op.drop_index('idx_enfermedad')

    op.drop_table('tratamientos')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index('idx_stock_product_branch')

    op.drop_table('stocks')
    with op.batch_alter_table('sintomas_enfermedades', schema=None) as batch_op:
        batch_op.drop_index('id_sintoma')

    op.drop_table('sintomas_enfermedades')
    with op.batch_alter_table('roles_permisos', schema=None) as batch_op:
        batch_op.drop_index('id_permiso')

    op.drop_table('roles_permisos')
    with op.batch_alter_table('remedios', schema=None) as batch_op:
        batch_op.drop_index('idx_tipo')
        batch_op.drop_index('idx_enfermedad')

    op.drop_table('remedios')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index('slug')
        batch_op.drop_index('idx_slug')
        batch_op.drop_index('idx_destacado')
        batch_op.drop_index('idx_categoria')
        batch_op.drop_index('idx_activo')
        batch_op.drop_index('ft_productos')
        batch_op.drop_index('codigo_producto')

    op.drop_table('productos')
    with op.batch_alter_table('parametros_nutricionales', schema=None) as batch_op:
        batch_op.drop_index('uk_tipo_etapa')
        batch_op.drop_index('id_etapa')

    op.drop_table('parametros_nutricionales')
    op.drop_table('orders')
    op.drop_table('growth_tables')
    with op.batch_alter_table('diagnostic_matrix', schema=None) as batch_op:
        batch_op.drop_index('idx_matrix_disease_symptom')

    op.drop_table('diagnostic_matrix')
    op.drop_table('users')
    with op.batch_alter_table('tipos_ave', schema=None) as batch_op:
        batch_op.drop_index('nombre_tipo')

    op.drop_table('tipos_ave')
    op.drop_table('symptoms')
    with op.batch_alter_table('sintomas', schema=None) as batch_op:
        batch_op.drop_index('idx_gravedad')
        batch_op.drop_index('ft_sintomas')

    op.drop_table('sintomas')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('uk_nombre_rol')
        batch_op.drop_index('nombre_rol')

    op.drop_table('roles')
    op.drop_table('products')
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.drop_index('nombre_permiso')
        batch_op.drop_index('idx_modulo')

    op.drop_table('permisos')
    with op.batch_alter_table('metodos_entrega', schema=None) as batch_op:
        batch_op.drop_index('nombre_metodo')

    op.drop_table('metodos_entrega')
    op.drop_table('genetic_lines')
    op.drop_table('feed_phases')
    with op.batch_alter_table('etapas_vida', schema=None) as batch_op:
        batch_op.drop_index('idx_orden')

    op.drop_table('etapas_vida')
    with op.batch_alter_table('estados_pedido', schema=None) as batch_op:
        batch_op.drop_index('nombre_estado')
        batch_op.drop_index('idx_orden')

    op.drop_table('estados_pedido')
    with op.batch_alter_table('enfermedades', schema=None) as batch_op:
        batch_op.drop_index('idx_tipo')
        batch_op.drop_index('ft_enfermedades')

    op.drop_table('enfermedades')
    op.drop_table('diseases')
    with op.batch_alter_table('configuracion_sistema', schema=None) as batch_op:
        batch_op.drop_index('idx_grupo')
        batch_op.drop_index('idx_clave')
        batch_op.drop_index('clave')

    op.drop_table('configuracion_sistema')
    with op.batch_alter_table('categorias_producto', schema=None) as batch_op:
        batch_op.drop_index('slug')
        batch_op.drop_index('nombre_categoria')
        batch_op.drop_index('idx_slug')
        batch_op.drop_index('idx_parent')

    op.drop_table('categorias_producto')
    with op.batch_alter_table('categorias_aveologia', schema=None) as batch_op:
        batch_op.drop_index('idx_orden')

    op.drop_table('categorias_aveologia')
    op.drop_table('branches')
    # ### end Alembic commands ###
