"""Creacion de tablas iniciales

Revision ID: 87034ea6954f
Revises: 
Create Date: 2026-06-28 19:49:31.006031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87034ea6954f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos_aveologia', schema=None) as batch_op:
        batch_op.alter_column('id_articulo',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_publicacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('articulos_aveologia_ibfk_1', 'categorias_aveologia', ['id_categoria'], ['id_categoria'])
        batch_op.create_foreign_key('articulos_aveologia_ibfk_2', 'usuarios', ['autor_id'], ['id_usuario'], ondelete='SET NULL')

    with op.batch_alter_table('atributos_producto', schema=None) as batch_op:
        batch_op.alter_column('id_atributo',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('atributos_producto_ibfk_1', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')

    with op.batch_alter_table('calificaciones', schema=None) as batch_op:
        batch_op.alter_column('id_calificacion',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_calificacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_producto_2'))
        batch_op.create_index('idx_producto', ['id_producto'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('calificaciones_ibfk_2', 'usuarios', ['id_cliente'], ['id_usuario'], ondelete='CASCADE')
        batch_op.create_foreign_key('calificaciones_ibfk_1', 'pedidos', ['id_pedido'], ['id_pedido'], ondelete='CASCADE')
        batch_op.create_foreign_key('calificaciones_ibfk_3', 'productos', ['id_producto'], ['id_producto'], ondelete='SET NULL')

    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.alter_column('id_carrito',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_agregado',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('carrito_ibfk_1', 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')
        batch_op.create_foreign_key('carrito_ibfk_2', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')

    with op.batch_alter_table('categorias_aveologia', schema=None) as batch_op:
        batch_op.alter_column('id_categoria',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('categorias_producto', schema=None) as batch_op:
        batch_op.alter_column('id_categoria_producto',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_slug_2'))
        batch_op.drop_index(batch_op.f('slug_2'))
        batch_op.create_index('idx_slug', ['slug'], unique=False)
        batch_op.create_index('slug', ['slug'], unique=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('categorias_producto_ibfk_1', 'categorias_producto', ['parent_id'], ['id_categoria_producto'], ondelete='SET NULL')

    with op.batch_alter_table('configuracion_sistema', schema=None) as batch_op:
        batch_op.alter_column('id_config',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('tipo_dato',
               existing_type=sa.TEXT(),
               type_=sa.Enum('string', 'Integer', 'boolean', 'json', name='configuracionsistematipodato'),
               existing_nullable=True,
               existing_server_default=sa.text("'string'"))

    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.alter_column('id_detalle',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_pedido_2'))
        batch_op.drop_index(batch_op.f('idx_producto_3'))
        batch_op.create_index('idx_pedido', ['id_pedido'], unique=False)
        batch_op.create_index('idx_producto', ['id_producto'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('detalle_pedido_ibfk_2', 'productos', ['id_producto'], ['id_producto'])
        batch_op.create_foreign_key('detalle_pedido_ibfk_1', 'pedidos', ['id_pedido'], ['id_pedido'], ondelete='CASCADE')

    with op.batch_alter_table('enfermedades', schema=None) as batch_op:
        batch_op.alter_column('id_enfermedad',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('tipo_enfermedad',
               existing_type=sa.TEXT(),
               type_=sa.Enum('viral', 'bacteriana', 'parasitaria', 'fungica', 'nutricional', 'ambiental', name='enfermedadestipoenfermedad'),
               existing_nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('contagiosidad',
               existing_type=sa.TEXT(),
               type_=sa.Enum('no_contagioso', 'baja', 'media', 'alta', name='enfermedadescontagiosidad'),
               existing_nullable=True,
               existing_server_default=sa.text("'media'"))

    with op.batch_alter_table('estados_pedido', schema=None) as batch_op:
        batch_op.alter_column('id_estado',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_orden_2'))
        batch_op.create_index('idx_orden', ['orden'], unique=False)

    with op.batch_alter_table('etapas_vida', schema=None) as batch_op:
        batch_op.alter_column('id_etapa',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_orden_3'))
        batch_op.create_index('idx_orden', ['orden'], unique=False)

    with op.batch_alter_table('historial_calculos', schema=None) as batch_op:
        batch_op.alter_column('id_calculo',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_calculo',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_usuario_2'))
        batch_op.create_index('idx_usuario', ['id_usuario'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('historial_calculos_ibfk_1', 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='SET NULL')
        batch_op.create_foreign_key('historial_calculos_ibfk_3', 'etapas_vida', ['id_etapa'], ['id_etapa'])
        batch_op.create_foreign_key('historial_calculos_ibfk_2', 'tipos_ave', ['id_tipo_ave'], ['id_tipo_ave'])

    with op.batch_alter_table('historial_pedido', schema=None) as batch_op:
        batch_op.alter_column('id_historial',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_cambio',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_fecha_2'))
        batch_op.drop_index(batch_op.f('idx_pedido_3'))
        batch_op.create_index('idx_fecha', ['fecha_cambio'], unique=False)
        batch_op.create_index('idx_pedido', ['id_pedido'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('historial_pedido_ibfk_1', 'pedidos', ['id_pedido'], ['id_pedido'], ondelete='CASCADE')
        batch_op.create_foreign_key('historial_pedido_ibfk_2', 'estados_pedido', ['id_estado'], ['id_estado'])
        batch_op.create_foreign_key('historial_pedido_ibfk_3', 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='SET NULL')

    with op.batch_alter_table('horarios_sucursal', schema=None) as batch_op:
        batch_op.alter_column('id_horario',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('dia_semana',
               existing_type=sa.TEXT(),
               type_=sa.Enum('lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo', name='horariossucursaldiasemana'),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('horarios_sucursal_ibfk_1', 'sucursales', ['id_sucursal'], ['id_sucursal'], ondelete='CASCADE')

    with op.batch_alter_table('imagenes_producto', schema=None) as batch_op:
        batch_op.alter_column('id_imagen',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_subida',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_producto_4'))
        batch_op.create_index('idx_producto', ['id_producto'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('imagenes_producto_ibfk_1', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')

    with op.batch_alter_table('inventario_sucursal', schema=None) as batch_op:
        batch_op.alter_column('id_inventario',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_producto_5'))
        batch_op.create_index('idx_producto', ['id_producto'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inventario_sucursal_ibfk_1', 'sucursales', ['id_sucursal'], ['id_sucursal'], ondelete='CASCADE')
        batch_op.create_foreign_key('inventario_sucursal_ibfk_2', 'productos', ['id_producto'], ['id_producto'], ondelete='CASCADE')

    with op.batch_alter_table('metodos_entrega', schema=None) as batch_op:
        batch_op.alter_column('id_metodo_entrega',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.alter_column('id_movimiento',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('tipo_movimiento',
               existing_type=sa.TEXT(),
               type_=sa.Enum('entrada', 'salida', 'ajuste', 'transferencia', 'devolucion', name='movimientosinventariotipomovimiento'),
               existing_nullable=False)
        batch_op.alter_column('fecha_movimiento',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('id_usuario_2'))
        batch_op.drop_index(batch_op.f('idx_fecha_3'))
        batch_op.drop_index(batch_op.f('idx_tipo_2'))
        batch_op.create_index('id_usuario', ['id_usuario'], unique=False)
        batch_op.create_index('idx_fecha', ['fecha_movimiento'], unique=False)
        batch_op.create_index('idx_tipo', ['tipo_movimiento'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('movimientos_inventario_ibfk_2', 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='SET NULL')
        batch_op.create_foreign_key('movimientos_inventario_ibfk_1', 'inventario_sucursal', ['id_inventario'], ['id_inventario'], ondelete='CASCADE')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.alter_column('id_notificacion',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('tipo_notificacion',
               existing_type=sa.TEXT(),
               type_=sa.Enum('pedido', 'sistema', 'promocion', 'alerta', name='notificacionestiponotificacion'),
               existing_nullable=True,
               existing_server_default=sa.text("'sistema'"))
        batch_op.drop_index(batch_op.f('idx_fecha_4'))
        batch_op.drop_index(batch_op.f('idx_usuario_3'))
        batch_op.create_index('idx_fecha', ['fecha_creacion'], unique=False)
        batch_op.create_index('idx_usuario', ['id_usuario'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notificaciones_ibfk_1', 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')

    with op.batch_alter_table('parametros_nutricionales', schema=None) as batch_op:
        batch_op.alter_column('id_parametro',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('id_etapa_2'))
        batch_op.create_index('id_etapa', ['id_etapa'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('parametros_nutricionales_ibfk_2', 'etapas_vida', ['id_etapa'], ['id_etapa'], ondelete='CASCADE')
        batch_op.create_foreign_key('parametros_nutricionales_ibfk_1', 'tipos_ave', ['id_tipo_ave'], ['id_tipo_ave'], ondelete='CASCADE')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('id_pedido',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_pedido',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('metodo_pago',
               existing_type=sa.TEXT(),
               type_=sa.Enum('efectivo', 'tarjeta', 'transferencia', 'yape', 'plin', name='pedidosmetodopago'),
               existing_nullable=True,
               existing_server_default=sa.text("'efectivo'"))
        batch_op.drop_index(batch_op.f('idx_fecha_5'))
        batch_op.drop_index(batch_op.f('idx_sucursal_2'))
        batch_op.create_index('idx_fecha', ['fecha_pedido'], unique=False)
        batch_op.create_index('idx_sucursal', ['id_sucursal'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pedidos_ibfk_4', 'metodos_entrega', ['id_metodo_entrega'], ['id_metodo_entrega'])
        batch_op.create_foreign_key('pedidos_ibfk_1', 'usuarios', ['id_cliente'], ['id_usuario'])
        batch_op.create_foreign_key('pedidos_ibfk_2', 'sucursales', ['id_sucursal'], ['id_sucursal'])
        batch_op.create_foreign_key('pedidos_ibfk_3', 'estados_pedido', ['id_estado'], ['id_estado'])

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.alter_column('id_permiso',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('unidad_medida',
               existing_type=sa.TEXT(),
               type_=sa.Enum('unidad', 'kg', 'lb', 'docena', 'caja', 'saco', name='productosunidadmedida'),
               existing_nullable=True,
               existing_server_default=sa.text("'unidad'"))
        batch_op.drop_index(batch_op.f('idx_categoria_2'))
        batch_op.drop_index(batch_op.f('idx_destacado_2'))
        batch_op.drop_index(batch_op.f('idx_slug_3'))
        batch_op.drop_index(batch_op.f('slug_3'))
        batch_op.create_index('idx_categoria', ['id_categoria_producto'], unique=False)
        batch_op.create_index('idx_destacado', ['destacado'], unique=False)
        batch_op.create_index('idx_slug', ['slug'], unique=False)
        batch_op.create_index('slug', ['slug'], unique=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('productos_ibfk_1', 'categorias_producto', ['id_categoria_producto'], ['id_categoria_producto'])

    with op.batch_alter_table('remedios', schema=None) as batch_op:
        batch_op.alter_column('id_remedio',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('tipo_remedio',
               existing_type=sa.TEXT(),
               type_=sa.Enum('casero', 'herbal', 'preventivo', 'paliativo', name='remediostiporemedio'),
               existing_nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('efectividad_estimada',
               existing_type=sa.TEXT(),
               type_=sa.Enum('baja', 'media', 'alta', name='remediosefectividadestimada'),
               existing_nullable=True,
               existing_server_default=sa.text("'media'"))
        batch_op.drop_index(batch_op.f('idx_tipo_3'))
        batch_op.create_index('idx_tipo', ['tipo_remedio'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('remedios_ibfk_1', 'enfermedades', ['id_enfermedad'], ['id_enfermedad'], ondelete='CASCADE')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('id_rol',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('roles_permisos', schema=None) as batch_op:
        batch_op.alter_column('fecha_asignacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('roles_permisos_ibfk_1', 'roles', ['id_rol'], ['id_rol'], ondelete='CASCADE')
        batch_op.create_foreign_key('roles_permisos_ibfk_2', 'permisos', ['id_permiso'], ['id_permiso'], ondelete='CASCADE')

    with op.batch_alter_table('sesiones_usuario', schema=None) as batch_op:
        batch_op.alter_column('id_sesion',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_usuario_4'))
        batch_op.create_index('idx_usuario', ['id_usuario'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sesiones_usuario_ibfk_1', 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')

    with op.batch_alter_table('sintomas', schema=None) as batch_op:
        batch_op.alter_column('id_sintoma',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('gravedad',
               existing_type=sa.TEXT(),
               type_=sa.Enum('leve', 'moderado', 'grave', 'critico', name='sintomasgravedad'),
               existing_nullable=True,
               existing_server_default=sa.text("'moderado'"))

    with op.batch_alter_table('sintomas_enfermedades', schema=None) as batch_op:
        batch_op.alter_column('frecuencia',
               existing_type=sa.TEXT(),
               type_=sa.Enum('raro', 'ocasional', 'frecuente', 'muy_frecuente', name='sintomasenfermedadesfrecuencia'),
               existing_nullable=True,
               existing_server_default=sa.text("'frecuente'"))
        batch_op.alter_column('intensidad',
               existing_type=sa.TEXT(),
               type_=sa.Enum('leve', 'moderado', 'severo', name='sintomasenfermedadesintensidad'),
               existing_nullable=True,
               existing_server_default=sa.text("'moderado'"))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sintomas_enfermedades_ibfk_1', 'enfermedades', ['id_enfermedad'], ['id_enfermedad'], ondelete='CASCADE')
        batch_op.create_foreign_key('sintomas_enfermedades_ibfk_2', 'sintomas', ['id_sintoma'], ['id_sintoma'], ondelete='CASCADE')

    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.alter_column('id_sucursal',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_activo_2'))
        batch_op.create_index('idx_activo', ['activo'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sucursales_ibfk_1', 'usuarios', ['id_encargado'], ['id_usuario'], ondelete='SET NULL')

    with op.batch_alter_table('tipos_ave', schema=None) as batch_op:
        batch_op.alter_column('id_tipo_ave',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('proposito',
               existing_type=sa.TEXT(),
               type_=sa.Enum('carne', 'huevos', 'dual', 'ornamental', name='tiposaveproposito'),
               existing_nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('tratamientos', schema=None) as batch_op:
        batch_op.alter_column('id_tratamiento',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('tipo_tratamiento',
               existing_type=sa.TEXT(),
               type_=sa.Enum('medicamento', 'vacuna', 'manejo', 'nutricional', 'quirurgico', name='tratamientostipotratamiento'),
               existing_nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_enfermedad_2'))
        batch_op.drop_index(batch_op.f('idx_tipo_4'))
        batch_op.create_index('idx_enfermedad', ['id_enfermedad'], unique=False)
        batch_op.create_index('idx_tipo', ['tipo_tratamiento'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tratamientos_ibfk_1', 'enfermedades', ['id_enfermedad'], ['id_enfermedad'], ondelete='CASCADE')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.create_index('idx_activo', ['activo'], unique=False)
        batch_op.create_index('idx_email', ['email'], unique=False)
        batch_op.create_index('idx_rol', ['id_rol'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('idx_rol')
        batch_op.drop_index('idx_email')
        batch_op.drop_index('idx_activo')
        batch_op.drop_index('email')

    with op.batch_alter_table('tratamientos', schema=None) as batch_op:
        batch_op.drop_constraint('tratamientos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'enfermedades', ['id_enfermedad'], ['id_enfermedad'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.drop_index('idx_tipo')
        batch_op.drop_index('idx_enfermedad')
        batch_op.create_index(batch_op.f('idx_tipo_4'), ['tipo_tratamiento'], unique=False)
        batch_op.create_index(batch_op.f('idx_enfermedad_2'), ['id_enfermedad'], unique=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('tipo_tratamiento',
               existing_type=sa.Enum('medicamento', 'vacuna', 'manejo', 'nutricional', 'quirurgico', name='tratamientostipotratamiento'),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id_tratamiento',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('tipos_ave', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('proposito',
               existing_type=sa.Enum('carne', 'huevos', 'dual', 'ornamental', name='tiposaveproposito'),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id_tipo_ave',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.drop_constraint('sucursales_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_encargado'], ['id_usuario'], onupdate='RESTRICT', ondelete='SET NULL')
        batch_op.drop_index('idx_activo')
        batch_op.create_index(batch_op.f('idx_activo_2'), ['activo'], unique=False)
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_sucursal',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sintomas_enfermedades', schema=None) as batch_op:
        batch_op.drop_constraint('sintomas_enfermedades_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('sintomas_enfermedades_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sintomas', ['id_sintoma'], ['id_sintoma'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'enfermedades', ['id_enfermedad'], ['id_enfermedad'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.alter_column('intensidad',
               existing_type=sa.Enum('leve', 'moderado', 'severo', name='sintomasenfermedadesintensidad'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'moderado'"))
        batch_op.alter_column('frecuencia',
               existing_type=sa.Enum('raro', 'ocasional', 'frecuente', 'muy_frecuente', name='sintomasenfermedadesfrecuencia'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'frecuente'"))

    with op.batch_alter_table('sintomas', schema=None) as batch_op:
        batch_op.alter_column('gravedad',
               existing_type=sa.Enum('leve', 'moderado', 'grave', 'critico', name='sintomasgravedad'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'moderado'"))
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_sintoma',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sesiones_usuario', schema=None) as batch_op:
        batch_op.drop_constraint('sesiones_usuario_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.drop_index('idx_usuario')
        batch_op.create_index(batch_op.f('idx_usuario_4'), ['id_usuario'], unique=False)
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_sesion',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('roles_permisos', schema=None) as batch_op:
        batch_op.drop_constraint('roles_permisos_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('roles_permisos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'permisos', ['id_permiso'], ['id_permiso'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['id_rol'], ['id_rol'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.alter_column('fecha_asignacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_rol',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('remedios', schema=None) as batch_op:
        batch_op.drop_constraint('remedios_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'enfermedades', ['id_enfermedad'], ['id_enfermedad'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.drop_index('idx_tipo')
        batch_op.create_index(batch_op.f('idx_tipo_3'), ['tipo_remedio'], unique=False)
        batch_op.alter_column('efectividad_estimada',
               existing_type=sa.Enum('baja', 'media', 'alta', name='remediosefectividadestimada'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'media'"))
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('tipo_remedio',
               existing_type=sa.Enum('casero', 'herbal', 'preventivo', 'paliativo', name='remediostiporemedio'),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id_remedio',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('productos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorias_producto', ['id_categoria_producto'], ['id_categoria_producto'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index('slug')
        batch_op.drop_index('idx_slug')
        batch_op.drop_index('idx_destacado')
        batch_op.drop_index('idx_categoria')
        batch_op.create_index(batch_op.f('slug_3'), ['slug'], unique=1)
        batch_op.create_index(batch_op.f('idx_slug_3'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_destacado_2'), ['destacado'], unique=False)
        batch_op.create_index(batch_op.f('idx_categoria_2'), ['id_categoria_producto'], unique=False)
        batch_op.alter_column('unidad_medida',
               existing_type=sa.Enum('unidad', 'kg', 'lb', 'docena', 'caja', 'saco', name='productosunidadmedida'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'unidad'"))
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_producto',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_permiso',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint('pedidos_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('pedidos_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('pedidos_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('pedidos_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'estados_pedido', ['id_estado'], ['id_estado'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'metodos_entrega', ['id_metodo_entrega'], ['id_metodo_entrega'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'usuarios', ['id_cliente'], ['id_usuario'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'sucursales', ['id_sucursal'], ['id_sucursal'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index('idx_sucursal')
        batch_op.drop_index('idx_fecha')
        batch_op.create_index(batch_op.f('idx_sucursal_2'), ['id_sucursal'], unique=False)
        batch_op.create_index(batch_op.f('idx_fecha_5'), ['fecha_pedido'], unique=False)
        batch_op.alter_column('metodo_pago',
               existing_type=sa.Enum('efectivo', 'tarjeta', 'transferencia', 'yape', 'plin', name='pedidosmetodopago'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'efectivo'"))
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('fecha_pedido',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_pedido',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('parametros_nutricionales', schema=None) as batch_op:
        batch_op.drop_constraint('parametros_nutricionales_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('parametros_nutricionales_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipos_ave', ['id_tipo_ave'], ['id_tipo_ave'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'etapas_vida', ['id_etapa'], ['id_etapa'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.drop_index('id_etapa')
        batch_op.create_index(batch_op.f('id_etapa_2'), ['id_etapa'], unique=False)
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_parametro',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint('notificaciones_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.drop_index('idx_usuario')
        batch_op.drop_index('idx_fecha')
        batch_op.create_index(batch_op.f('idx_usuario_3'), ['id_usuario'], unique=False)
        batch_op.create_index(batch_op.f('idx_fecha_4'), ['fecha_creacion'], unique=False)
        batch_op.alter_column('tipo_notificacion',
               existing_type=sa.Enum('pedido', 'sistema', 'promocion', 'alerta', name='notificacionestiponotificacion'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'sistema'"))
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_notificacion',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_constraint('movimientos_inventario_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('movimientos_inventario_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventario_sucursal', ['id_inventario'], ['id_inventario'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'], onupdate='RESTRICT', ondelete='SET NULL')
        batch_op.drop_index('idx_tipo')
        batch_op.drop_index('idx_fecha')
        batch_op.drop_index('id_usuario')
        batch_op.create_index(batch_op.f('idx_tipo_2'), ['tipo_movimiento'], unique=False)
        batch_op.create_index(batch_op.f('idx_fecha_3'), ['fecha_movimiento'], unique=False)
        batch_op.create_index(batch_op.f('id_usuario_2'), ['id_usuario'], unique=False)
        batch_op.alter_column('fecha_movimiento',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('tipo_movimiento',
               existing_type=sa.Enum('entrada', 'salida', 'ajuste', 'transferencia', 'devolucion', name='movimientosinventariotipomovimiento'),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id_movimiento',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('metodos_entrega', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_metodo_entrega',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('inventario_sucursal', schema=None) as batch_op:
        batch_op.drop_constraint('inventario_sucursal_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('inventario_sucursal_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id_producto'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'sucursales', ['id_sucursal'], ['id_sucursal'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.drop_index('idx_producto')
        batch_op.create_index(batch_op.f('idx_producto_5'), ['id_producto'], unique=False)
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_inventario',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('imagenes_producto', schema=None) as batch_op:
        batch_op.drop_constraint('imagenes_producto_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id_producto'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.drop_index('idx_producto')
        batch_op.create_index(batch_op.f('idx_producto_4'), ['id_producto'], unique=False)
        batch_op.alter_column('fecha_subida',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_imagen',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('horarios_sucursal', schema=None) as batch_op:
        batch_op.drop_constraint('horarios_sucursal_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sucursales', ['id_sucursal'], ['id_sucursal'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.alter_column('dia_semana',
               existing_type=sa.Enum('lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo', name='horariossucursaldiasemana'),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id_horario',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('historial_pedido', schema=None) as batch_op:
        batch_op.drop_constraint('historial_pedido_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('historial_pedido_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('historial_pedido_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pedidos', ['id_pedido'], ['id_pedido'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'estados_pedido', ['id_estado'], ['id_estado'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'], onupdate='RESTRICT', ondelete='SET NULL')
        batch_op.drop_index('idx_pedido')
        batch_op.drop_index('idx_fecha')
        batch_op.create_index(batch_op.f('idx_pedido_3'), ['id_pedido'], unique=False)
        batch_op.create_index(batch_op.f('idx_fecha_2'), ['fecha_cambio'], unique=False)
        batch_op.alter_column('fecha_cambio',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_historial',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('historial_calculos', schema=None) as batch_op:
        batch_op.drop_constraint('historial_calculos_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('historial_calculos_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('historial_calculos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'], onupdate='RESTRICT', ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'etapas_vida', ['id_etapa'], ['id_etapa'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'tipos_ave', ['id_tipo_ave'], ['id_tipo_ave'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index('idx_usuario')
        batch_op.create_index(batch_op.f('idx_usuario_2'), ['id_usuario'], unique=False)
        batch_op.alter_column('fecha_calculo',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_calculo',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('etapas_vida', schema=None) as batch_op:
        batch_op.drop_index('idx_orden')
        batch_op.create_index(batch_op.f('idx_orden_3'), ['orden'], unique=False)
        batch_op.alter_column('id_etapa',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('estados_pedido', schema=None) as batch_op:
        batch_op.drop_index('idx_orden')
        batch_op.create_index(batch_op.f('idx_orden_2'), ['orden'], unique=False)
        batch_op.alter_column('id_estado',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('enfermedades', schema=None) as batch_op:
        batch_op.alter_column('contagiosidad',
               existing_type=sa.Enum('no_contagioso', 'baja', 'media', 'alta', name='enfermedadescontagiosidad'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'media'"))
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('tipo_enfermedad',
               existing_type=sa.Enum('viral', 'bacteriana', 'parasitaria', 'fungica', 'nutricional', 'ambiental', name='enfermedadestipoenfermedad'),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id_enfermedad',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.drop_constraint('detalle_pedido_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('detalle_pedido_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id_producto'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'pedidos', ['id_pedido'], ['id_pedido'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.drop_index('idx_producto')
        batch_op.drop_index('idx_pedido')
        batch_op.create_index(batch_op.f('idx_producto_3'), ['id_producto'], unique=False)
        batch_op.create_index(batch_op.f('idx_pedido_2'), ['id_pedido'], unique=False)
        batch_op.alter_column('id_detalle',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('configuracion_sistema', schema=None) as batch_op:
        batch_op.alter_column('tipo_dato',
               existing_type=sa.Enum('string', 'Integer', 'boolean', 'json', name='configuracionsistematipodato'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'string'"))
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_config',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('categorias_producto', schema=None) as batch_op:
        batch_op.drop_constraint('categorias_producto_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorias_producto', ['parent_id'], ['id_categoria_producto'], onupdate='RESTRICT', ondelete='SET NULL')
        batch_op.drop_index('slug')
        batch_op.drop_index('idx_slug')
        batch_op.create_index(batch_op.f('slug_2'), ['slug'], unique=1)
        batch_op.create_index(batch_op.f('idx_slug_2'), ['slug'], unique=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_categoria_producto',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('categorias_aveologia', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_categoria',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.drop_constraint('carrito_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('carrito_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id_producto'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('fecha_agregado',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_carrito',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('calificaciones', schema=None) as batch_op:
        batch_op.drop_constraint('calificaciones_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('calificaciones_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('calificaciones_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pedidos', ['id_pedido'], ['id_pedido'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuarios', ['id_cliente'], ['id_usuario'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id_producto'], onupdate='RESTRICT', ondelete='SET NULL')
        batch_op.drop_index('idx_producto')
        batch_op.create_index(batch_op.f('idx_producto_2'), ['id_producto'], unique=False)
        batch_op.alter_column('fecha_calificacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_calificacion',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('atributos_producto', schema=None) as batch_op:
        batch_op.drop_constraint('atributos_producto_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id_producto'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.alter_column('id_atributo',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('articulos_aveologia', schema=None) as batch_op:
        batch_op.drop_constraint('articulos_aveologia_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('articulos_aveologia_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['autor_id'], ['id_usuario'], onupdate='RESTRICT', ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'categorias_aveologia', ['id_categoria'], ['id_categoria'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.alter_column('fecha_actualizacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('fecha_publicacion',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id_articulo',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
